### PR TITLE
ogr2ogr version to maintain geometry information

### PR DESCRIPTION
**Pull request by n0rdlicht**
Switch to ogr2ogr for conversion to csv in order to maintain geometry information as WKT column.

### CODE REVIEW

**Review by loleg — COMMENTED** [review]
The proposal is sound. Couple of questions:
- the option to extract data directly from SQLite might still be useful, e.g. on platforms where `ogr2ogr` is not supported, or if all the user wants is to get some basic stats - we could leave it in the `Makefile` just for reference
- please confirm why you've dropped the `primaryindex` column. Yes, I see that there is a `baumnummer` field, but it might be worth bringing it to the top since it's customary to have a clear primary key - especially one that may be referenced in other settings.
- the `awk` query in the preview-extract step needs a comment, or be changed to the simpler `head` command, otherwise it looks like we might be doing data manipulation there.

Thanks!

**Comment by n0rdlicht** [comment]
Thanks, Oleg.

* agreed, might just need a second processed resource or how would you solve different use cases in this instance? Would not solve software compatibility issues
* ogr2ogr afik doesn't extract that from the sqlite database unfortunately, however a `fid` (e.g. to easily produce a valid geojson) would make sense to have for sure, will check for options
* true. couldn't get `head` to work over here, but more than happy to swap for simpler/cleaner solutions

**Comment by n0rdlicht** [comment]
So, I should look into any of the three points?

**Review by loleg — COMMENTED** [review]
Let's keep the `sqlite3` function in a separate Make steps just for reference, but the default makestep and preview should be the approach that conserves the geodata.

**Comment by n0rdlicht** [comment]
Added a second make path `nogeom`.

**Comment by loleg** [comment]
Tested, works, thanks.

**Pull request merged**
